description: "Universal configuration"

# ----------------------------
# Global Hyperparameters
# ----------------------------
defaults:
  batch_size: 32
  num_epochs: 50
  loss_function: cross_entropy
  optimizer: adamw
  lr: 0.001 # 1e-3
  seed: 42
# ----------------------------
# Scheduler Hyperparameters
# ----------------------------
scheduler_params:
  mode: min
  factor: 0.5
  patience: 4
  threshold: 0.0001 # 1e-4
  cooldown: 1
  min_lr: 0.000001 # 1e-6
