# src/configs/gradual_unfreeze.yaml
description: "Gradual unfreezing configuration"

# ----------------------------
# Global Hyperparameters
# ----------------------------
defaults:
  batch_size: 32
  num_epochs: 50
  loss_function: cross_entropy
  optimizer: adamw
  lr: 0.0001 # Lower initial LR for gradual unfreezing
  weight_decay: 0.01
  seed: 42
  early_stopping_patience: 10

# ----------------------------
# Scheduler Hyperparameters
# ----------------------------
scheduler_params:
  mode: min
  factor: 0.5
  patience: 3
  threshold: 0.0001
  cooldown: 1
  min_lr: 0.000001
