# src/configs/test.yaml
description: "Test run config - fastest possible"

# ----------------------------
# Global Hyperparameters
# ----------------------------
defaults:
  batch_size: 8 # smaller batch for faster iterations
  num_epochs: 50 # only 1 epoch
  loss_function: cross_entropy
  optimizer: adamw
  lr: 0.001 # can increase for faster convergence in test
  weight_decay: 0.01 # Standard weight decay for test runs
  seed: 42
  early_stopping_patience: 50 # disable early stopping for test
# ----------------------------
# Scheduler Hyperparameters
scheduler_params:
  mode: min
  factor: 0.5
  patience: 1
  threshold: 0.01
  cooldown: 0
  min_lr: 0.0001
